[package]
name = "ewf-image-fuzz"
version = "0.0.0"
publish = false
edition = "2024"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
ewf-image = { path = ".." }
aff4-image = { path = "../crates/aff4-image" }
tempfile = "3"

[workspace]
members = ["."]

[[bin]]
name = "ewf_read"
path = "fuzz_targets/ewf_read.rs"
test = false
doc = false
bench = false

[[bin]]
name = "aff4_read"
path = "fuzz_targets/aff4_read.rs"
test = false
doc = false
bench = false
